name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Fix permissions
        run: chmod +x dockerfiles/start.sh

      - name: Build Docker image
        run: docker build --tag=swimpool-android --file=dockerfiles/Dockerfile .

      - name: Build APK
        run: |
          docker run --env-file dockerfiles/env.list \
                     -v $PWD:/home/user \
                     swimpool-android buildozer android debug
        timeout-minutes: 120

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: swimpool-apk
          path: bin/*.apk
          retention-days: 30